//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public short bank_id { get; set; }
        public Nullable<decimal> summary { get; set; }
        public Nullable<decimal> precent { get; set; }
        public Nullable<decimal> penni { get; set; }
        public Nullable<System.DateTime> datebank { get; set; }
        public Nullable<double> foryears { get; set; }
    }
}
