//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public byte ingr_ID { get; set; }
        public Nullable<byte> produciya { get; set; }
        public Nullable<short> syrie { get; set; }
        public Nullable<double> kol_vo { get; set; }
    
        public virtual Gotov_product Gotov_product { get; set; }
        public virtual Syrie Syrie1 { get; set; }
    }
}
