//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procent
    {
        public byte procent_id { get; set; }
        public Nullable<double> Procent1 { get; set; }
        public Nullable<double> Procent_zarplaty { get; set; }
        public Nullable<double> Procent_banka { get; set; }
    }
}
