//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodstvo
    {
        public int proizvodstvo_ID { get; set; }
        public Nullable<byte> product { get; set; }
        public Nullable<double> kol_vo { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<short> sotrudnik { get; set; }
    
        public virtual Gotov_product Gotov_product { get; set; }
        public virtual Sotrudnik Sotrudnik1 { get; set; }
    }
}
