//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public short syrie_id { get; set; }
        public string name { get; set; }
        public Nullable<byte> ed_izmer { get; set; }
        public Nullable<double> summa { get; set; }
        public Nullable<double> kol_vo { get; set; }
    }
}
