//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zarplata
    {
        public byte id_zarplaty { get; set; }
        public Nullable<short> id_sotrudnika { get; set; }
        public Nullable<int> mesyac { get; set; }
        public Nullable<int> god { get; set; }
        public Nullable<decimal> oklad { get; set; }
        public Nullable<double> procent_oklada { get; set; }
        public Nullable<decimal> obwaya_summa { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
